language: node_js
node_js:
  - "6"
  - "5"
  - "4"
sudo: false
services:
  - postgresql
addons:
  postgresql: "9.4"
env:
  - DB_USER=postgres DB_PASS=''
before_script:
  - psql -c 'create database mppg;' -U postgres
